# Generated by Django 5.0.2 on 2024-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('tName', models.CharField(max_length=40)),
                ('tEmail', models.EmailField(max_length=30)),
            ],
        ),
    ]
